export const products = [
  {
    id: "0",
    title:
      "Fastrack FS1 Pro Smartwatch | 1.96 inch Super AMOLED Arched Display with High Resolution of 410X502 | Singlesync BT Calling | Nitrofast Charging|110+ Sports Modes | 200+ Watchfaces",
    rating: 4.1,
    mrp: 7995,
    price: 2499,
    Brand: "Fastrack",
    Review: 36,
    quantity: 40,
    light: true,
    image: [
      "https://m.media-amazon.com/images/I/61mPyZEfN7L._SY355_.jpg",
      "https://m.media-amazon.com/images/I/712yHjFkAaL._SY355_.jpg",
      "https://m.media-amazon.com/images/I/61n4DmjV3oL._SY355_.jpg",
      "https://m.media-amazon.com/images/I/71unB5xjSpL._SY355_.jpg",
      "https://m.media-amazon.com/images/I/61n70qUAqQL._SY355_.jpg",
      "https://m.media-amazon.com/images/I/61TUaS7rLBL._SY355_.jpg",
    ],
    type: "electronic",
    details: {
      Brand: "Fastrack",
      "Model Name": "Fastrack FS1 Pro",
      Style: "Modern",
      Colour: "Classic Blue",
      "Screen Size": "1.96 Inches",
    },
    description: [
      "World's First 1.96 inch Super AMOLED Arched Display with Always On Display and is ready to style your wrist with bright pixel resolution for a sharper experience and brand new amazing colours",
      "SingleSync BT Calling with Favourite Contacts storage (Android - 100, iOS - 50) and Quick Replies (Android)",
      "NitroFast Charging with 10 min charge to fuel up 1 day of battery. Your watch has a battery of up to 7 Days (Up to 3 Days with BT Calling)",
      "Advanced 110+ Sports Modes, 200+ Watchfaces, In-Built Games, AI Voice Assistant and many more handy features at a single tap",
      "Health Monitoring with Auto Stress monitor, 24x7 Heart Rate, Sleep Tracker, Spo2 and Women's Health",
    ],
    additional: null,
  },
  {
    id: "1",
    title:
      "FUR JADEN Anti Theft Number Lock Backpack Bag with 15.6 Inch Laptop Compartment, USB Charging Port & Organizer Pocket for Men Women Boys Girls",
    rating: 4.2,
    mrp: 2000,
    price: 649,
    Brand: "FUR JADEN",
    Review: 104,
    quantity: 36,
    light: true,
    image: [
      "https://m.media-amazon.com/images/I/61egMfcDWlL._SX522_.jpg",
      "https://m.media-amazon.com/images/I/716eUpQQoHL._SX522_.jpg",
      "https://m.media-amazon.com/images/I/81qCxeIJmZL._SX522_.jpg",
      "https://m.media-amazon.com/images/I/91i0LFDI5mL._SX522_.jpg",
      "https://m.media-amazon.com/images/I/81xZHoPRZCL._SX522_.jpg",
      "https://m.media-amazon.com/images/I/711zuBhz0yL._SX522_.jpg",
    ],
    type: "Bags",
    details: {
      "Care instructions": "Wipe with Damp Cloth",
      "Country of Origin": "India",
    },
    description: [
      "Number Lock: This Fur Jaden Anti Theft laptop backpack comes equipped with a Number Lock. This helps keep your laptop and other belongings safe when you need to leave your bag unattended in a public space. The number lock sequence can be changed and customised by your directly.",
      "USB Charging Port: Now charge your devices on the go with your new Fur Jaden backpack without the hassle of carrying a bulk power bank in your pocket/ hand at all times.",
      "Ergonomic Design: This backpack has been designed to ensure equal weight distribution on your shoulders along with padded shoulder straps and breathable air mesh on the back.",
      "Dimension: 42 CM (L) x 30 CM (W) x 18 CM (D). Storage Capacity: 25L. Weight: 600 Grams; Warranty: 1 Year Manufacturer Warranty against Manufacturing Defects",
      "Age Range Description: Adult; Closure Type: Zipper; Lining Description: Polyester",
    ],
    additional: {
      Manufacturer:
        "FUR JADEN, Fur Jaden, 3C Jai Hind Bld, Dr AM Road, Bhuleshwar, Mumbai 400002",
      Packer:
        "Fur Jaden, 3C Jai Hind Bld, Dr AM Road, Bhuleshwar, Mumbai 400002",
      "Item Weight": "600 g",
      "Item Dimensions LxWxH": "30 x 18 x 42 Centimeters",
      "Net Quantity": "1.00 Unit",
      "Generic Name": "Anti Theft Laptop Backpack",
    },
  },
  {
    id: "2",
    title: "Moccasin EM-02 Men's Casual Shoes",
    rating: 4,
    mrp: 4000,
    price: 3699,
    Brand: "Moccasin",
    Review: 48,
    quantity: 80,
    light: true,
    image: [
      "https://m.media-amazon.com/images/I/713sRfW7PkL._SY500_.jpg",
      "https://m.media-amazon.com/images/I/61swUsdWRXL._SY500_.jpg",
      "https://m.media-amazon.com/images/I/71oyNmWeqaL._SY500_.jpg",
      "https://m.media-amazon.com/images/I/71rlYSO5rXL._SY500_.jpg",
      "https://m.media-amazon.com/images/I/71W8T-qFJJL._SY500_.jpg",
      "https://m.media-amazon.com/images/I/714HZ6A7C8L._SY500_.jpg",
    ],
    type: "Men",
    details: {
      "Closure type": "Pull-On",
      "Heel type": "No Heel",
      "Water resistance level": "Water Resistant",
      "Sole material": "Rubber",
      Style: "Moccasin EM-02",
      "Outer material": "Leather",
      "Country of Origin": "India",
    },
    description: [
      "Designed with your comfort in mind, our moccasins feature a luxurious memory foam footbed with leather lining, offering plush cushioning and support with each stride.",
      "Versatile and stylish, these moccasins effortlessly elevate any outfit, transitioning seamlessly from casual to formal occasions adding a touch of timeless elegance to any ensemble. Step into style and comfort with our meticulously crafted moccasin leather shoes.",
      "The convenient slip-on design ensures hassle-free wear, perfect for those hectic mornings or when you're on the go.",
    ],
    additional: {
      Manufacturer:
        "Torpedo Shoes (P) Ltd., Torpedo Shoes (P) Ltd. Contact details- 6390060000",
      Packer: "Torpedo Shoes (P) Ltd.",
      "Net Quantity": "1 Count",
    },
  },
  {
    id: "3",
    title: "Campus Men's OXYFIT (N) Walking Shoes",
    rating: 4.1,
    mrp: 999,
    price: 529,
    Brand: "Campus",
    Review: 56,
    quantity: 4,
    light: true,
    image: [
      "https://m.media-amazon.com/images/I/61ePa5fEKnL._SY625_.jpg",
      "https://m.media-amazon.com/images/I/61dU0vkPK8S._SY500_.jpg",
      "https://m.media-amazon.com/images/I/61b+PO-KuqL._SY500_.jpg",
      "https://m.media-amazon.com/images/I/71Spy9mHrIL._SY500_.jpg",
      "https://m.media-amazon.com/images/I/61Jf8W5zOfL._SY500_.jpg",
    ],
    type: "Men",
    details: {
      "Material type": "Mesh",
      "Closure type": "Pull-On",
      "Heel type": "Flat",
      "Water resistance level": "Not Water Resistant",
      "Sole material": "Rubber",
      Style: "Sneaker",
      "Country of Origin": "India",
    },
    description: [
      "Shoes' Upper- Slip into style and ease with these men's casual slip-on shoes. The breathable mesh upper keeps your feet fresh and comfortable. These slip-ons are easy to wear and are perfect for those who hate the hassle of tying laces. Suitable for your need, be it college, office, or casual dates – these shoes for men are versatile enough for any occasion!",
      "Shoes' Outsole- Pillo Foam sole ensures your steps are cushioned with every landing. Take every stride comfortably with the impact protection of the outsole. These shoes for men are a perfect match for your on-the-go lifestyle.",
      "Shoes' Insole- Experience customized comfort with the Memory Foam insole. Say goodbye to discomfort as these casual shoes adapt to your unique foot shape and offer an incredible footbed for you to walk on.",
      "Style The Shoes- Dress up for office days with chinos or go laid-back with jeans for weekends. These slip-on shoes effortlessly elevate your look for every event.",
      "Clean Your Shoes- Keeping these cool shoes clean is a breeze. Wipe them with a damp cloth for daily maintenance. For deeper cleaning, use mild soap and water. And they are ready to rock your style, any day!",
    ],
    additional: {
      Manufacturer:
        "Campus, Campus Shoes,D-1, Rohtak Road, Udyog Nagar, Opp. Peera Garhi Metro Station Gate No 2, New Delhi, Delhi 110041,ph no- 01143272500",
      Packer:
        "Campus Shoes,D-1, Rohtak Road, Udyog Nagar, Opp. Peera Garhi Metro Station Gate No 2, New Delhi, Delhi 110041,ph no- 01143272500",
      "Item Weight": "700 g",
      "Item Dimensions LxWxH": "30.5 x 21.5 x 11.2 Centimeters",
      "Net Quantity": "1 Set",
      "Generic Name": "Walking Shoes",
    },
  },
  {
    id: "4",
    title: "Apple iPhone 13 (128GB) - Blue",
    rating: 4.6,
    mrp: 59900,
    price: 49999,
    Brand: "Apple",
    Review: 150,
    quantity: 9,
    light: true,
    image: [
      "https://m.media-amazon.com/images/I/71xb2xkN5qL._SX522_.jpg",
      "https://m.media-amazon.com/images/I/61CAYVr34QL._SX522_.jpg",
      "https://m.media-amazon.com/images/I/81junVbiuyL._SX522_.jpg",
      "https://m.media-amazon.com/images/I/71G44HUh7yL._SX522_.jpg",
      "https://m.media-amazon.com/images/I/81-hHbjQGSL._SX522_.jpg",
      "https://m.media-amazon.com/images/I/61wIVtrz54L._SX522_.jpg",
    ],
    type: "electronic",
    details: {
      Brand: "Apple",
      Colour: "Blue",
      "Model Name": "iPhone",
      "Network Service Provider": "Unlocked for All Carriers",
      "Operating System": "iOS 14",
      "Cellular Technology": "5G",
    },
    description: [
      "15 cm (6.1-inch) Super Retina XDR display",
      "Cinematic mode adds shallow depth of field and shifts focus automatically in your videos",
      "Advanced dual-camera system with 12MP Wide and Ultra Wide cameras; Photographic Styles, Smart HDR 4, Night mode, 4K Dolby Vision HDR recording",
      "12MP TrueDepth front camera with Night mode, 4K Dolby Vision HDR recording",
      "A15 Bionic chip for lightning-fast performance",
    ],
    additional: {
      Display:
        "6.1-inch (15.5 cm diagonal) Super Retina XDR display with True Tone",
      Capacity: "64GB, 128GB, 256GB",
      "Splash, Water, and Dust Resistant":
        "All-glass and surgical-grade stainless steel design, water and dust resistant (rated IP68)",
      "Camera and Video":
        "Dual 12MP cameras with Portrait mode, Depth Control, Portrait Lighting, Smart HDR, and 4K Dolby Vision HDR video up to 30 fps",
      "Front Camera":
        "12MP TrueDepth front camera with Portrait mode, Depth Control, Portrait Lighting, and Smart HDR 4",
      "Power and Battery":
        "Video playback:Up to 19 hours, Video playback (streamed):Up to 15 hours, Audio playback:Up to 75 hours, 20W adapter or higher (sold separately), Fast-charge capable: Up to 50% charge in around 30 minutes with 20W adapter or higher",
      Warranty:
        "Apple-branded hardware product and accessories contained in the original packaging (“Apple Product”) come with a One-Year Limited Warranty. See apple.com/in/legal/warranty for more information.",
    },
  },
  {
    id: "5",
    title:
      "Nikon D7500 20.9MP Digital SLR Camera (Black) with AF-S DX NIKKOR 18-140mm f/3.5-5.6G ED VR Lens",
    rating: 4.4,
    mrp: 94950,
    price: 93950,
    Brand: "Nikon",
    Review: 56,
    quantity: 15,
    light: true,
    image: [
      "https://m.media-amazon.com/images/I/71iKNJ6rVIL._SY355_.jpg",
      "https://m.media-amazon.com/images/I/51g0J5dj7GL._SY355_.jpg",
      "https://m.media-amazon.com/images/I/51mg-oAhtHL._SY355_.jpg",
      "https://m.media-amazon.com/images/I/515+vgB6OOL._SY355_.jpg",
    ],
    type: "electronic",
    details: {
      Brand: "Nikon",
      "Model Name": "D7500",
      "Maximum Webcam Image Resolution": "20.9 MP",
      "Photo Sensor Size": "APS-C fps",
      "Image Stabilisation": "Optical",
      "Maximum Shutter Speed": "1/8000 to 30 Seconds",
      "Minimum Shutter Speed": "30 Seconds",
      "Metering Description": "3D Color Matrix",
      "Exposure Control Type": "Automatic",
      "Form Factor": "DSLR",
    },
    description: [
      "20.9MP DX-Format CMOS Sensor, SnapBridge Bluetooth and Wi-Fi;4K UHD Video Recording at 30 fps",
      "Multi-CAM 3500FX II 51-Point AF System",
      "Native ISO 51200, Expanded ISO 1,640,000",
      "180k-Pixel RGB Sensor and Group Area AF; Country of Origin: Japan",
      "Compatible Mountings: Nikon F; Hardware Interface: Audio Video Port",
    ],
    additional: null,
  },
];

// export const products = [
//   {
//     id: 1,
//     name: "Product 1",
//     price: 50,
//     image: "https://via.placeholder.com/150",
//     quantity: 1,
//   },
//   {
//     id: 2,
//     name: "Product 2",
//     price: 100,
//     image: "https://via.placeholder.com/150",
//     quantity: 1,
//   },
// ];
